using GHOST.Application.Day6; using GHOST.Application.Authentication; using GHOST.Domain.Entities; using GHOST.Infrastructure.Persistence; using Microsoft.Data.Sqlite; using Serilog;
namespace GHOST.Infrastructure.Day6;
public sealed class SqliteBackupService(AppDbContext dbContext, ICurrentUserContext currentUser): IBackupService
{
 public async Task<string>CreateBackupAsync(string db,BackupOptions o,CancellationToken ct=default){var actor=Require("Manager");if(!await ValidateAsync(db,ct))throw new InvalidOperationException("Source database is invalid.");Directory.CreateDirectory(o.DirectoryPath);var target=Path.Combine(o.DirectoryPath,$"ghost-{DateTimeOffset.UtcNow:yyyyMMdd-HHmmssfff}-{Guid.NewGuid():N}.db");await using(var source=new SqliteConnection($"Data Source={db};Pooling=False")){await source.OpenAsync(ct);await using var destination=new SqliteConnection($"Data Source={target};Pooling=False");await destination.OpenAsync(ct);source.BackupDatabase(destination);}if(!await ValidateAsync(target,ct)){File.Delete(target);throw new InvalidOperationException("Backup validation failed.");}Rotate(o);await Audit(actor.Id,"BackupCreated","Backup",target,ct);Log.Information("Database backup created at {BackupPath}",target);return target;}
 public async Task<bool>ValidateAsync(string p,CancellationToken ct=default){if(!File.Exists(p))return false;try{await using var c=new SqliteConnection($"Data Source={p};Mode=ReadOnly;Pooling=False");await c.OpenAsync(ct);await using(var q=c.CreateCommand()){q.CommandText="PRAGMA integrity_check;";var integrity=(string?)await q.ExecuteScalarAsync(ct);if(integrity!="ok")return false;q.CommandText="SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name IN ('Devices','Sessions','Users');";return Convert.ToInt32(await q.ExecuteScalarAsync(ct))==3;}}catch{return false;}}
 public async Task RestoreAsync(string db,string backup,BackupOptions o,CancellationToken ct=default){var actor=Require("Admin");if(!await ValidateAsync(backup,ct))throw new InvalidOperationException("Selected backup is invalid.");var safety=await CreateBackupAsyncInternal(db,new BackupOptions(Path.Combine(o.DirectoryPath,"pre-restore"),o.RetentionCount),ct);var stage=db+".restore-stage";try{File.Copy(backup,stage,true);if(!await ValidateAsync(stage,ct))throw new InvalidOperationException("Staged restore is invalid.");File.Copy(stage,db,true);if(!await ValidateAsync(db,ct))throw new InvalidOperationException("Restored database verification failed.");await Audit(actor.Id,"BackupRestored","Backup",backup,ct);Log.Information("Database restored from {BackupPath}; prior database saved as {SafetyBackup}",backup,safety);}catch{if(File.Exists(safety))File.Copy(safety,db,true);throw;}finally{if(File.Exists(stage))File.Delete(stage);}}
 private async Task<string>CreateBackupAsyncInternal(string db,BackupOptions o,CancellationToken ct){if(!await ValidateAsync(db,ct))throw new InvalidOperationException("Source database is invalid.");Directory.CreateDirectory(o.DirectoryPath);var target=Path.Combine(o.DirectoryPath,$"ghost-{DateTimeOffset.UtcNow:yyyyMMdd-HHmmssfff}-{Guid.NewGuid():N}.db");await using(var source=new SqliteConnection($"Data Source={db};Pooling=False")){await source.OpenAsync(ct);await using var destination=new SqliteConnection($"Data Source={target};Pooling=False");await destination.OpenAsync(ct);source.BackupDatabase(destination);}if(!await ValidateAsync(target,ct)){File.Delete(target);throw new InvalidOperationException("Backup validation failed.");}Rotate(o);return target;}
 private AuthenticatedUser Require(string role){var actor=currentUser.RequireAuthenticated();if(role=="Manager"?(actor.IsInRole("Manager")||actor.IsInRole("Admin")):actor.IsInRole("Admin"))return actor;throw new UnauthorizedAccessException("Operation is not authorized.");}
 private async Task Audit(Guid actorId,string action,string type,string value,CancellationToken ct){dbContext.AuditLogs.Add(new AuditLog{ActorId=actorId,Action=action,EntityType=type,NewValue=value});await dbContext.SaveChangesAsync(ct);}
 private static void Rotate(BackupOptions o){var files=new DirectoryInfo(o.DirectoryPath).GetFiles("ghost-*.db").OrderByDescending(x=>x.CreationTimeUtc).ToList();foreach(var f in files.Skip(Math.Max(1,o.RetentionCount)))f.Delete();}
}
