using GHOST.Application.Day5; using GHOST.Domain.Entities; using GHOST.Domain.Enums; using GHOST.Infrastructure.Persistence; using Microsoft.EntityFrameworkCore;
namespace GHOST.Infrastructure.Day5;
public sealed class Day5Service(AppDbContext db) : IDay5Service
{
 public async Task<ProductCategory> CreateCategoryAsync(Guid a,string n,CancellationToken ct=default){await Role(a,"Admin",ct);if(string.IsNullOrWhiteSpace(n)||await db.ProductCategories.AnyAsync(x=>x.Name==n.Trim(),ct))throw new ArgumentException("Invalid category.");var x=new ProductCategory{Name=n.Trim()};db.ProductCategories.Add(x);await SaveAudit(a,"CategoryCreated","ProductCategory",x.Id,null,x.Name,ct);return x;}
 public async Task<Product> CreateProductAsync(Guid a,ProductRequest r,CancellationToken ct=default){await Role(a,"Admin",ct);if(string.IsNullOrWhiteSpace(r.Name)||r.SellingPrice<0||r.CostPrice<0||r.MinimumStockLevel<0||!await db.ProductCategories.AnyAsync(x=>x.Id==r.CategoryId&&x.IsActive,ct))throw new ArgumentException("Invalid product.");var p=new Product{Name=r.Name.Trim(),CategoryId=r.CategoryId,SellingPrice=r.SellingPrice,CostPrice=r.CostPrice,MinimumStockLevel=r.MinimumStockLevel};db.Products.Add(p);await SaveAudit(a,"ProductCreated","Product",p.Id,null,p.Name,ct);return p;}
 public async Task SetProductActiveAsync(Guid a,Guid id,bool active,CancellationToken ct=default){await Role(a,"Admin",ct);var p=await Product(id,ct);p.IsActive=active;await SaveAudit(a,active?"ProductEnabled":"ProductDeactivated","Product",id,null,active.ToString(),ct);}
 public async Task<InventoryTransaction> ChangeStockAsync(Guid a,InventoryRequest r,CancellationToken ct=default){await Role(a,r.Type is InventoryTransactionType.Adjustment or InventoryTransactionType.Waste ? "Manager":"Cashier",ct);if(r.Quantity<=0||string.IsNullOrWhiteSpace(r.Reason))throw new ArgumentException("Quantity and reason required.");await using var tx=await db.Database.BeginTransactionAsync(ct);var p=await Product(r.ProductId,ct);var delta=r.Type is InventoryTransactionType.Purchase or InventoryTransactionType.Return? r.Quantity:-r.Quantity;if(p.StockQuantity+delta<0)throw new InvalidOperationException("Insufficient stock.");var it=new InventoryTransaction{ProductId=p.Id,Type=r.Type,Quantity=delta,BeforeQuantity=p.StockQuantity,AfterQuantity=p.StockQuantity+delta,Reason=r.Reason.Trim(),CreatedById=a};p.StockQuantity+=delta;db.InventoryTransactions.Add(it);await SaveAudit(a,"Inventory"+r.Type,"Product",p.Id,it.BeforeQuantity.ToString(),it.AfterQuantity.ToString(),ct,r.Reason);await tx.CommitAsync(ct);return it;}
 public async Task<IReadOnlyList<Product>> GetLowStockAsync(CancellationToken ct=default)=>await db.Products.AsNoTracking().Where(x=>x.StockQuantity<=x.MinimumStockLevel).OrderBy(x=>x.StockQuantity).ToListAsync(ct);
 public async Task<Order> CompleteOrderAsync(Guid a,CompleteOrderRequest r,CancellationToken ct=default){await Role(a,"Cashier",ct);if(r.Items.Count==0||r.AmountReceived<0||r.OrderDiscount<0)throw new ArgumentException("Invalid order.");await using var tx=await db.Database.BeginTransactionAsync(ct);var shift=await db.Shifts.SingleOrDefaultAsync(x=>x.IsOpen,ct)??throw new InvalidOperationException("An open shift is required.");var order=new Order{CustomerId=r.CustomerId,SessionId=r.SessionId,CreatedById=a,DiscountAmount=r.OrderDiscount};foreach(var line in r.Items){if(line.Quantity<=0||line.Discount<0)throw new ArgumentException("Invalid item.");var p=await Product(line.ProductId,ct);if(!p.IsActive||p.StockQuantity<line.Quantity)throw new InvalidOperationException("Product unavailable or insufficient stock.");var total=p.SellingPrice*line.Quantity-line.Discount;if(total<0)throw new InvalidOperationException("Item discount exceeds amount.");p.StockQuantity-=line.Quantity;order.Items.Add(new OrderItem{ProductId=p.Id,Quantity=line.Quantity,UnitPrice=p.SellingPrice,Discount=line.Discount,Total=total});db.InventoryTransactions.Add(new InventoryTransaction{ProductId=p.Id,Type=InventoryTransactionType.Sale,Quantity=-line.Quantity,BeforeQuantity=p.StockQuantity+line.Quantity,AfterQuantity=p.StockQuantity,Reason="POS order",CreatedById=a});}order.TotalAmount=order.Items.Sum(x=>x.Total)+r.Items.Sum(x=>x.Discount);order.FinalAmount=order.Items.Sum(x=>x.Total)-r.OrderDiscount;if(order.FinalAmount<0||r.AmountReceived<order.FinalAmount)throw new InvalidOperationException("Insufficient payment.");order.AmountReceived=r.AmountReceived;order.Change=r.AmountReceived-order.FinalAmount;db.Orders.Add(order);db.CashTransactions.Add(new CashTransaction{ShiftId=shift.Id,Amount=order.FinalAmount,Type=CashTransactionType.Sale,Reference=order.Id.ToString(),Reason="POS order",UserId=a});await SaveAudit(a,"OrderCompleted","Order",order.Id,null,order.FinalAmount.ToString(),ct);await tx.CommitAsync(ct);return order;}
 public async Task<Shift> OpenShiftAsync(Guid a,decimal cash,CancellationToken ct=default){await Role(a,"Cashier",ct);if(cash<0||await db.Shifts.AnyAsync(x=>x.IsOpen,ct))throw new InvalidOperationException("Invalid opening shift.");var s=new Shift{OpenedById=a,OpeningCash=cash};db.Shifts.Add(s);db.CashTransactions.Add(new CashTransaction{ShiftId=s.Id,Amount=cash,Type=CashTransactionType.Opening,Reason="Opening cash",UserId=a});await SaveAudit(a,"ShiftOpened","Shift",s.Id,null,cash.ToString(),ct);return s;}
 public async Task<Shift> CloseShiftAsync(Guid a,Guid id,CloseShiftRequest r,CancellationToken ct=default){await Role(a,"Cashier",ct);if(r.ActualCash<0)throw new ArgumentException("Invalid cash.");var s=await db.Shifts.SingleOrDefaultAsync(x=>x.Id==id&&x.IsOpen,ct)??throw new InvalidOperationException("Shift is not open.");var expected=s.OpeningCash+await db.CashTransactions.Where(x=>x.ShiftId==id&&x.Type!=CashTransactionType.Opening&&x.Type!=CashTransactionType.Closing).SumAsync(x=>(decimal?)x.Amount,ct)??s.OpeningCash;var diff=r.ActualCash-expected;if(Math.Abs(diff)>0.01m&&string.IsNullOrWhiteSpace(r.DifferenceReason))throw new InvalidOperationException("Difference reason required.");s.IsOpen=false;s.ClosedById=a;s.ClosedAt=DateTimeOffset.UtcNow;s.ExpectedCash=expected;s.ActualCash=r.ActualCash;s.Difference=diff;s.DifferenceReason=r.DifferenceReason;db.CashTransactions.Add(new CashTransaction{ShiftId=id,Amount=r.ActualCash,Type=CashTransactionType.Closing,Reason=r.DifferenceReason??"Closing cash",UserId=a});await SaveAudit(a,"ShiftClosed","Shift",id,expected.ToString(),r.ActualCash.ToString(),ct,r.DifferenceReason);return s;}
 private async Task<Product> Product(Guid id,CancellationToken ct)=>await db.Products.SingleOrDefaultAsync(x=>x.Id==id,ct)??throw new KeyNotFoundException("Product not found."); private async Task Role(Guid a,string need,CancellationToken ct){var rs=await db.Users.AsNoTracking().Where(x=>x.Id==a&&x.IsActive).SelectMany(x=>x.Roles).Select(x=>x.Name).ToListAsync(ct);if(!(need=="Cashier"?rs.Any(x=>x is "Cashier" or "Manager" or "Admin"):need=="Manager"?rs.Any(x=>x is "Manager" or "Admin"):rs.Contains("Admin")))throw new UnauthorizedAccessException();} private async Task SaveAudit(Guid a,string ac,string et,Guid id,string? old,string? nw,CancellationToken ct,string? reason=null){db.AuditLogs.Add(new AuditLog{ActorId=a,Action=ac,EntityType=et,EntityId=id,OldValue=old,NewValue=nw,Reason=reason});await db.SaveChangesAsync(ct);}
}
