using GHOST.Application.Day4;
using GHOST.Domain.Entities;
using GHOST.Domain.Enums;
using GHOST.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;

namespace GHOST.Infrastructure.Day4;

public sealed class Day4Service(AppDbContext db) : IDay4Service
{
    public async Task<Customer> CreateCustomerAsync(Guid actor, CreateCustomerRequest r, CancellationToken ct = default)
    { await RequireAsync(actor, "Cashier", ct); ValidateCustomer(r.Name, r.Phone); if (r.Phone is not null && await db.Customers.AnyAsync(x => x.Phone == r.Phone.Trim(), ct)) throw new InvalidOperationException("Phone is already assigned to a customer."); var c = new Customer { Name = r.Name.Trim(), Phone = Clean(r.Phone), Notes = Clean(r.Notes), CreatedById = actor }; db.Customers.Add(c); await AuditSave(actor, "CustomerCreated", "Customer", c.Id, null, c.Name, ct); return c; }
    public async Task<Customer> UpdateCustomerAsync(Guid actor, Guid id, UpdateCustomerRequest r, CancellationToken ct = default)
    { await RequireAsync(actor, "Cashier", ct); ValidateCustomer(r.Name, r.Phone); var c = await CustomerAsync(id, ct); if (r.Phone is not null && await db.Customers.AnyAsync(x => x.Id != id && x.Phone == r.Phone.Trim(), ct)) throw new InvalidOperationException("Phone is already assigned to a customer."); var old = $"{c.Name}|{c.Phone}"; c.Name = r.Name.Trim(); c.Phone = Clean(r.Phone); c.Notes = Clean(r.Notes); await AuditSave(actor, "CustomerUpdated", "Customer", c.Id, old, $"{c.Name}|{c.Phone}", ct); return c; }
    public async Task<IReadOnlyList<Customer>> SearchCustomersAsync(string term, CancellationToken ct = default) { var q = term.Trim(); return await db.Customers.AsNoTracking().Where(x => q == "" || x.Phone == q || x.Name.Contains(q)).OrderByDescending(x => x.Phone == q).ThenBy(x => x.Name).Take(100).ToListAsync(ct); }
    public async Task<CustomerProfile> GetCustomerProfileAsync(Guid id, LoyaltyRule rule, CancellationToken ct = default) { var c = await CustomerAsync(id, ct); var sessions = await db.Sessions.AsNoTracking().Where(x => x.CustomerId == id).OrderByDescending(x => x.StartedAt).ToListAsync(ct); var cutoff = DateTimeOffset.UtcNow.AddDays(-rule.FrequentWindowDays); return new CustomerProfile(c, sessions, sessions.Count(x => x.Status == SessionStatus.Completed && x.StartedAt >= cutoff) >= rule.FrequentVisitThreshold); }
    public async Task SetCustomerBlockedAsync(Guid actor, Guid id, bool blocked, string reason, CancellationToken ct = default) { await RequireAsync(actor, "Manager", ct); if (string.IsNullOrWhiteSpace(reason)) throw new ArgumentException("A reason is required."); var c = await CustomerAsync(id, ct); var old = c.IsBlocked.ToString(); c.IsBlocked = blocked; await AuditSave(actor, blocked ? "CustomerBlocked" : "CustomerUnblocked", "Customer", id, old, blocked.ToString(), ct, reason); }
    public async Task<Discount> RequestDiscountAsync(Guid actor, DiscountRequest r, CancellationToken ct = default)
    { await RequireAsync(actor, "Cashier", ct); ValidateDiscount(r); decimal? amount = null; if (r.SessionId is not null) { var s = await db.Sessions.SingleOrDefaultAsync(x => x.Id == r.SessionId, ct) ?? throw new KeyNotFoundException("Session not found."); if (s.Status != SessionStatus.Completed || s.TotalAmount is null) throw new InvalidOperationException("Discounts apply only to completed sessions."); if (await db.Discounts.AnyAsync(x => x.SessionId == r.SessionId, ct)) throw new InvalidOperationException("A discount was already requested for this session."); amount = r.Type == DiscountType.Percentage ? decimal.Round(s.TotalAmount.Value * r.Value / 100m, 2) : r.Value; if (amount > s.TotalAmount) throw new InvalidOperationException("Discount exceeds the applicable amount."); }
        var d = new Discount { CustomerId = r.CustomerId, SessionId = r.SessionId, Type = r.Type, Value = r.Value, Reason = r.Reason.Trim(), RequestedById = actor, AppliedAmount = amount }; db.Discounts.Add(d); await AuditSave(actor, "DiscountRequested", "Discount", d.Id, null, r.Type.ToString(), ct, r.Reason); return d; }
    public async Task ApproveDiscountAsync(Guid actor, Guid id, CancellationToken ct = default) { await RequireAsync(actor, "Manager", ct); var d = await db.Discounts.SingleOrDefaultAsync(x => x.Id == id, ct) ?? throw new KeyNotFoundException("Discount not found."); if (d.Status != DiscountStatus.Requested) throw new InvalidOperationException("Only requested discounts can be approved."); d.Status = DiscountStatus.Approved; d.ApprovedById = actor; d.ApprovedAt = DateTimeOffset.UtcNow; await AuditSave(actor, "DiscountApproved", "Discount", id, "Requested", "Approved", ct, d.Reason); }
    public async Task RejectDiscountAsync(Guid actor, Guid id, string reason, CancellationToken ct = default) { await RequireAsync(actor, "Manager", ct); if (string.IsNullOrWhiteSpace(reason)) throw new ArgumentException("A rejection reason is required."); var d = await db.Discounts.SingleAsync(x => x.Id == id, ct); if (d.Status != DiscountStatus.Requested) throw new InvalidOperationException("Only requested discounts can be rejected."); d.Status = DiscountStatus.Rejected; d.ApprovedById = actor; d.ApprovedAt = DateTimeOffset.UtcNow; await AuditSave(actor, "DiscountRejected", "Discount", id, "Requested", "Rejected", ct, reason); }
    public async Task<LoyaltyTransaction> AddLoyaltyAsync(Guid actor, Guid customerId, LoyaltyTransactionType type, int points, string reason, CancellationToken ct = default) { await RequireAsync(actor, type == LoyaltyTransactionType.Adjustment ? "Manager" : "Cashier", ct); if (string.IsNullOrWhiteSpace(reason) || points == 0) throw new ArgumentException("Points and reason are required."); var c = await CustomerAsync(customerId, ct); var delta = type is LoyaltyTransactionType.Redeem or LoyaltyTransactionType.Expiration ? -Math.Abs(points) : points; if (c.LoyaltyPoints + delta < 0) throw new InvalidOperationException("Loyalty balance cannot become negative."); c.LoyaltyPoints += delta; var t = new LoyaltyTransaction { CustomerId = customerId, Type = type, Points = delta, Reason = reason.Trim(), CreatedById = actor }; db.LoyaltyTransactions.Add(t); await AuditSave(actor, "Loyalty" + type, "Customer", customerId, null, delta.ToString(), ct, reason); return t; }
    public async Task<Gift> IssueGiftAsync(Guid actor, Guid customerId, GiftPeriod period, string description, CancellationToken ct = default) { await RequireAsync(actor, "Manager", ct); if (string.IsNullOrWhiteSpace(description)) throw new ArgumentException("Description is required."); await CustomerAsync(customerId, ct); if (period is GiftPeriod.Weekly or GiftPeriod.Monthly) { var cutoff = period == GiftPeriod.Weekly ? DateTimeOffset.UtcNow.AddDays(-7) : DateTimeOffset.UtcNow.AddMonths(-1); var issued = await db.Gifts.Where(x => x.CustomerId == customerId && x.Period == period).Select(x => x.IssuedAt).ToListAsync(ct); if (issued.Any(x => x >= cutoff)) throw new InvalidOperationException("Gift already issued in this period."); } var g = new Gift { CustomerId = customerId, Period = period, Description = description.Trim(), IssuedById = actor }; db.Gifts.Add(g); await AuditSave(actor, "GiftIssued", "Gift", g.Id, null, description, ct); return g; }
    public async Task RedeemGiftAsync(Guid actor, Guid id, CancellationToken ct = default) { await RequireAsync(actor, "Cashier", ct); var g = await db.Gifts.SingleOrDefaultAsync(x => x.Id == id, ct) ?? throw new KeyNotFoundException("Gift not found."); if (g.Status != GiftStatus.Issued) throw new InvalidOperationException("Gift is not redeemable."); g.Status = GiftStatus.Redeemed; g.RedeemedById = actor; g.RedeemedAt = DateTimeOffset.UtcNow; await AuditSave(actor, "GiftRedeemed", "Gift", id, "Issued", "Redeemed", ct); }
    public async Task<GiftCard> CreateGiftCardAsync(Guid actor, CreateGiftCardRequest r, CancellationToken ct = default) { await RequireAsync(actor, "Admin", ct); if (r.RewardType == GiftCardRewardType.CashValue && (r.CashValue is null || r.CashValue <= 0)) throw new ArgumentException("Cash gift cards require a positive value."); var card = new GiftCard { Code = await NewCardCode(ct), RewardType = r.RewardType, CashValue = r.CashValue, Description = Clean(r.Description), ExpiresAt = r.ExpiresAt, CreatedById = actor }; db.GiftCards.Add(card); await AuditSave(actor, "GiftCardCreated", "GiftCard", card.Id, null, card.Code, ct); return card; }
    public async Task RedeemGiftCardAsync(Guid actor, string code, CancellationToken ct = default) { await RequireAsync(actor, "Cashier", ct); var card = await db.GiftCards.SingleOrDefaultAsync(x => x.Code == code.Trim().ToUpperInvariant(), ct) ?? throw new KeyNotFoundException("Gift card not found."); if (card.Status != GiftCardStatus.Active || card.ExpiresAt < DateTimeOffset.UtcNow) throw new InvalidOperationException("Gift card is not redeemable."); card.Status = GiftCardStatus.Used; card.UsedById = actor; card.UsedAt = DateTimeOffset.UtcNow; await AuditSave(actor, "GiftCardRedeemed", "GiftCard", card.Id, "Active", "Used", ct); }
    public async Task<Offer> CreateOfferAsync(Guid actor, CreateOfferRequest r, CancellationToken ct = default) { await RequireAsync(actor, "Admin", ct); if (string.IsNullOrWhiteSpace(r.Name) || r.EndDate < r.StartDate || r.Value < 0 || (r.DiscountType == DiscountType.Percentage && r.Value > 100)) throw new ArgumentException("Invalid offer."); var o = new Offer { Name = r.Name.Trim(), StartDate = r.StartDate, EndDate = r.EndDate, DaysOfWeek = r.DaysOfWeek, StartTime = r.StartTime, EndTime = r.EndTime, DiscountType = r.DiscountType, DiscountValue = r.Value, ApplicableDeviceTypes = r.DeviceTypes, MinimumDurationMinutes = r.MinimumDurationMinutes, MaximumUsage = r.MaximumUsage, CreatedById = actor }; db.Offers.Add(o); await AuditSave(actor, "OfferCreated", "Offer", o.Id, null, o.Name, ct); return o; }
    public async Task SetOfferActiveAsync(Guid actor, Guid id, bool active, CancellationToken ct = default) { await RequireAsync(actor, "Admin", ct); var o = await db.Offers.SingleOrDefaultAsync(x => x.Id == id, ct) ?? throw new KeyNotFoundException("Offer not found."); o.Active = active; await AuditSave(actor, active ? "OfferEnabled" : "OfferDisabled", "Offer", id, null, active.ToString(), ct); }
    private async Task AuditSave(Guid actor, string action, string type, Guid id, string? old, string? @new, CancellationToken ct, string? reason = null) { db.AuditLogs.Add(new AuditLog { ActorId = actor, Action = action, EntityType = type, EntityId = id, OldValue = old, NewValue = @new, Reason = reason }); await db.SaveChangesAsync(ct); }
    private async Task<Customer> CustomerAsync(Guid id, CancellationToken ct) => await db.Customers.SingleOrDefaultAsync(x => x.Id == id, ct) ?? throw new KeyNotFoundException("Customer not found.");
    private async Task RequireAsync(Guid actor, string minimum, CancellationToken ct) { var roles = await db.Users.AsNoTracking().Where(x => x.Id == actor && x.IsActive).SelectMany(x => x.Roles).Select(x => x.Name).ToListAsync(ct); var allowed = minimum switch { "Cashier" => roles.Any(x => x is "Cashier" or "Manager" or "Admin"), "Manager" => roles.Any(x => x is "Manager" or "Admin"), _ => roles.Contains("Admin") }; if (!allowed) throw new UnauthorizedAccessException("Operation is not authorized."); }
    private static void ValidateCustomer(string name, string? phone) { if (string.IsNullOrWhiteSpace(name) || name.Length > 150 || phone?.Length > 30) throw new ArgumentException("Invalid customer data."); }
    private static void ValidateDiscount(DiscountRequest r) { if (r.Value < 0 || string.IsNullOrWhiteSpace(r.Reason) || (r.Type == DiscountType.Percentage && r.Value > 100)) throw new ArgumentException("Invalid discount."); }
    private static string? Clean(string? value) => string.IsNullOrWhiteSpace(value) ? null : value.Trim();
    private async Task<string> NewCardCode(CancellationToken ct) { string code; do { code = $"GIFT-{Guid.NewGuid().ToString("N")[..4].ToUpperInvariant()}-{Guid.NewGuid().ToString("N")[..4].ToUpperInvariant()}"; } while (await db.GiftCards.AnyAsync(x => x.Code == code, ct)); return code; }
}
