using GHOST.Application.Day6; using GHOST.Domain.Entities; using GHOST.Domain.Enums; using GHOST.Infrastructure.Day6; using GHOST.Infrastructure.Persistence; using Microsoft.EntityFrameworkCore;
using GHOST.Application.Authentication;
namespace GHOST.Tests;
public sealed class Day6ServiceTests: IAsyncLifetime
{ private string dir=null!,path=null!;private AppDbContext db=null!;public async Task InitializeAsync(){dir=Path.Combine(Path.GetTempPath(),"ghost-day6-"+Guid.NewGuid());Directory.CreateDirectory(dir);path=Path.Combine(dir,"ghost.db");db=new(new DbContextOptionsBuilder<AppDbContext>().UseSqlite($"Data Source={path};Pooling=False").Options);await new DatabaseInitializer(db).InitializeAsync();var role=await db.Roles.SingleAsync(x=>x.Name=="Admin");db.Users.Add(new User{Username="admin",PasswordHash="x",Roles=[role]});await db.SaveChangesAsync();}public async Task DisposeAsync(){await db.DisposeAsync();Directory.Delete(dir,true);} 
[Fact]public async Task Backup_validates_rotates_and_restore_preserves_safety_copy(){var admin=await db.Users.SingleAsync();var user=new TestCurrentUserContext(new AuthenticatedUser(admin.Id,admin.Username,new HashSet<string>{"Admin"}));var backup=new SqliteBackupService(db,user);var options=new BackupOptions(Path.Combine(dir,"backups"),1);var first=await backup.CreateBackupAsync(path,options);Assert.True(await backup.ValidateAsync(first));var second=await backup.CreateBackupAsync(path,options);Assert.Single(Directory.GetFiles(options.DirectoryPath,"ghost-*.db"));await db.DisposeAsync();db=new(new DbContextOptionsBuilder<AppDbContext>().UseSqlite($"Data Source={path};Pooling=False").Options);backup=new SqliteBackupService(db,user);await backup.RestoreAsync(path,second,options);Assert.True(await backup.ValidateAsync(path));File.WriteAllText(Path.Combine(dir,"bad.db"),"not sqlite");Assert.False(await backup.ValidateAsync(Path.Combine(dir,"bad.db")));}
[Fact]public async Task Reports_use_actual_completed_sessions_and_low_stock(){var d=await db.Devices.FirstAsync();var s=new Session{DeviceId=d.Id,StartedAt=DateTimeOffset.UtcNow.AddHours(-2),EndedAt=DateTimeOffset.UtcNow.AddHours(-1),Status=SessionStatus.Completed,RatePerHour=100,TotalAmount=100};db.Sessions.Add(s);var cat=new ProductCategory{Name="D"};db.ProductCategories.Add(cat);var p=new Product{Name="P",Category=cat,SellingPrice=10,CostPrice=5,StockQuantity=1,MinimumStockLevel=2};db.Products.Add(p);await db.SaveChangesAsync();var report=await new ReportingService(db).GetDashboardAsync(new(DateTimeOffset.UtcNow.AddDays(-1),DateTimeOffset.UtcNow.AddDays(1)));Assert.Equal(100,report.Revenue);Assert.Equal(1,report.Sessions);Assert.Equal(1,report.LowStock);Assert.NotEmpty(report.Utilization);}
 private sealed class TestCurrentUserContext(AuthenticatedUser user):ICurrentUserContext{public AuthenticatedUser? Current=>user;public AuthenticatedUser RequireAuthenticated()=>user;public bool IsInRole(string role)=>user.IsInRole(role);}
}
